name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # master branch'e her push işleminde çalışacak
  pull_request:
    branches:
      - master  # master branch'e pull request gönderildiğinde çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu ortamında çalışacak
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # GitHub repo içeriğini checkout yapar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Docker Buildx'i kurar

      - name: Log in to DockerHub
        uses: docker/login-action@v2  # DockerHub'a giriş yapar
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub kullanıcı adı (GitHub secrets'ta saklanmalı)
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub şifresi (GitHub secrets'ta saklanmalı)

      - name: Build Docker image
        run: |
          docker build -t my-node-app .  # Docker imajını oluşturur

      - name: Push Docker image to DockerHub
        run: |
          docker push my-node-app  # Docker imajını DockerHub'a yükler
